package pl.polsl.viktordidyk.baconcipher.servlets;

import java.io.*;
import java.util.Date;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.*;
import pl.polsl.viktordidyk.baconcipher.model.Transcriptor;
/**
 * Main class of the servlet displaying current time, date and image. Site
 * generated by servlet is refreshed every 10 seconds.
 *
 * @author Gall Anonim
 * @version 1.0
 */
@WebServlet("/startDecryption")
public class DecryptServlet extends HttpServlet {
//    Transcriptor transcriptor;
    
    @Override
    public void doPost(HttpServletRequest request, HttpServletResponse response)
            throws IOException, ServletException {
//        transcriptor = new Transcriptor();
        response.setContentType("text/plain; charset=ISO-8859-2");
        PrintWriter out = response.getWriter();

        out.println("Passed parameters:");

        String messageToDecode = request.getParameter("decryption");
        String test = request.getParameter("decryption");
        out.println(test);
        
//        String decryptedMessage = transcriptor.decrypt(messageToDecode);
//        out.println(decryptedMessage);
    }
}
